export const marketplaceStrings = {
  home: {
    title: 'बाजारपेठ',
    subtitle: 'शेतकरी ते शेतकरी थेट व्यवहार',
    searchPlaceholder: 'पिके, बियाणे, खते किंवा यंत्रे शोधा...',
    produceCardTitle: 'शेतमाल',
    produceCardSubtitle: 'महाराष्ट्रातील शेतकऱ्यांकडून थेट खरेदी करा',
    produceCardAction: 'शेतमाल पहा',
    productCardTitle: 'शेती साहित्य',
    productCardSubtitle: 'बियाणे • खते • औषधे • यंत्रे',
    productCardAction: 'साहित्य पहा',
    savedListings: 'जतन केलेले',
    myListings: 'माझ्या जाहिराती',
    sellSomething: 'नवीन जाहिरात',
  },
  listings: {
    produceTitle: 'शेतमाल',
    productsTitle: 'शेती साहित्य',
    loading: 'जाहिराती लोड होत आहेत…',
    errorTitle: 'काहीतरी चुकले',
    retry: 'पुन्हा प्रयत्न करा',
    emptyTitle: 'कोणतीही जाहिरात सापडली नाही',
    emptyMessage:
      'सध्या कोणतीही जाहिरात उपलब्ध नाही.\n\nकृपया नंतर पुन्हा प्रयत्न करा.',
    searchEmptyMessage: 'आपल्या शोधाशी जुळणारी कोणतीही जाहिरात सापडली नाही.',
    loadMore: 'अजून लोड होत आहे…',
    categoryAll: 'सर्व',
  },
  categories: {
    Produce: 'शेतमाल',
    Seeds: 'बियाणे',
    Fertilizers: 'खते',
    Pesticides: 'कीटकनाशके',
    'Farm Machinery': 'शेती यंत्रे',
    Tools: 'साधने',
    Irrigation: 'सिंचन',
    'Crop Protection': 'पीक संरक्षण',
  },
  status: {
    ACTIVE: 'सक्रिय',
    SOLD: 'विकले',
    ARCHIVED: 'संग्रहित',
  },
  detail: {
    title: 'जाहिरात तपशील',
    description: 'वर्णन',
    category: 'प्रकार',
    price: 'किंमत',
    quantity: 'प्रमाण',
    seller: 'विक्रेता',
    district: 'जिल्हा',
    phone: 'मोबाईल',
    posted: 'प्रकाशित',
    callSeller: 'संपर्क करा',
    whatsappSeller: 'व्हॉट्सअॅप',
    loading: 'जाहिरात लोड होत आहे…',
    errorTitle: 'जाहिरात लोड करता आली नाही',
    brand: 'ब्रँड',
    stock: 'साठा',
    crop: 'पीक',
    harvestDate: 'कापणीची तारीख',
    ownerActions: 'आपल्या कृती',
    soldMessage: 'ही जाहिरात विकली म्हणून चिन्हांकित केली आहे.\nती आता खरेदीदारांना दिसणार नाही.',
    archivedMessage:
      'ही जाहिरात संग्रहित केली आहे.\nसंग्रहित जाहिराती फक्त आपल्यालाच दिसतात.',
    editListing: 'जाहिरात संपादित करा',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    archive: 'संग्रहित करा',
    inStock: 'साठा उपलब्ध',
  },
  create: {
    title: 'नवीन जाहिरात',
    editTitle: 'जाहिरात संपादित करा',
    listingType: 'जाहिरात प्रकार',
    produce: 'शेतमाल',
    product: 'शेती साहित्य',
    crop: 'पीक',
    cropPlaceholder: 'पीक निवडा',
    favoriteCropsTitle: '⭐ तुमची प्रमुख पिके',
    allCropsTitle: 'सर्व पिके',
    quantity: 'प्रमाण',
    unit: 'एकक',
    expectedPrice: 'अपेक्षित किंमत',
    harvestDate: 'कापणीची तारीख',
    harvestDatePlaceholder: 'तारीख निवडा',
    selectDate: 'निवडा',
    productName: 'उत्पादनाचे नाव',
    productNamePlaceholder: 'उदा. हायब्रिड टोमॅटो बियाणे',
    brand: 'ब्रँड',
    brandPlaceholder: 'उदा. महिको',
    category: 'प्रकार',
    stock: 'साठा',
    price: 'किंमत',
    description: 'वर्णन',
    descriptionPlaceholder: 'आपल्या जाहिरातीबद्दल माहिती लिहा…',
    imagesPlaceholder: 'छायाचित्र अपलोड लवकरच उपलब्ध होईल',
    publish: 'जाहिरात प्रकाशित करा',
    update: 'जाहिरात अद्यतनित करा',
    publishing: 'प्रकाशित होत आहे…',
    updating: 'अद्यतनित होत आहे…',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    archive: 'संग्रहित करा',
    archiving: 'संग्रहित होत आहे…',
    districtAuto: (district: string) => `📍 जिल्हा: ${district} (आपोआप निवडलेले)`,
    districtLoading: '📍 जिल्हा लोड होत आहे…',
  },
  myListings: {
    title: 'माझ्या जाहिराती',
    active: 'सक्रिय',
    sold: 'विकले',
    archived: 'संग्रहित',
    edit: 'संपादन करा',
    archive: 'संग्रहित करा',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    myListingBadge: 'माझी जाहिरात',
    emptyTitle: 'आपण अद्याप कोणतीही जाहिरात तयार केलेली नाही.',
    emptyMessage: 'आजच पहिली जाहिरात द्या.',
  },
  saved: {
    title: 'जतन केलेल्या जाहिराती',
    emptyTitle: 'आपण अद्याप कोणतीही जाहिरात जतन केलेली नाही.',
    emptyMessage: 'जाहिरातीवर हृदय चिन्ह दाबून जतन करा.',
    save: 'जतन करा',
  },
  lifecycle: {
    markSoldTitle: 'विकले म्हणून चिन्हांकित करायचे?',
    markSoldMessage:
      'ही जाहिरात बाजारपेठेत दिसणार नाही.\nआपण ती माझ्या जाहिराती मध्ये पाहू शकता.',
    markSoldConfirm: 'विकले म्हणून चिन्हांकित करा',
    archiveTitle: 'जाहिरात संग्रहित करायची?',
    archiveMessage:
      'संग्रहित जाहिराती बाजारपेठेत दिसणार नाहीत.\nते माझ्या जाहिराती मध्ये उपलब्ध राहतील.',
    archiveConfirm: 'संग्रहित करा',
    cancel: 'रद्द करा',
    markedSold: 'जाहिरात विकली म्हणून चिन्हांकित केली.',
    archived: 'जाहिरात यशस्वीरित्या संग्रहित केली.',
    unableMarkSold: 'जाहिरात विकली म्हणून चिन्हांकित करता आली नाही.',
    unableArchive: 'जाहिरात संग्रहित करता आली नाही.',
    unableSave: 'जाहिरात जतन करता आली नाही.',
    whatsappUnavailable: 'या उपकरणावर व्हॉट्सअॅप उपलब्ध नाही.',
  },
  errors: {
    timeout: 'वेळ संपला. कृपया पुन्हा प्रयत्न करा.',
    network: 'इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
    backendUnavailable: 'बाजारपेठ तात्पुरती उपलब्ध नाही. कृपया नंतर प्रयत्न करा.',
    validation: 'कृपया तपशील तपासा आणि पुन्हा प्रयत्न करा.',
    generic: 'ही कृती पूर्ण करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
    requiredField: 'हे फील्ड भरणे आवश्यक आहे',
    invalidPrice: 'वैध किंमत प्रविष्ट करा',
    invalidQuantity: 'वैध प्रमाण प्रविष्ट करा',
  },
  images: {
    addPhoto: 'फोटो जोडा',
    takePhoto: '📷 फोटो काढा',
    chooseGallery: '🖼️ गॅलरीमधून निवडा',
    removePhoto: 'फोटो हटवा',
    maxReached: 'जास्तीत जास्त ३ फोटो जोडता येतील.',
    maxSelected: 'जास्तीत जास्त ३ फोटो निवडा.',
    uploading: 'फोटो अपलोड होत आहेत...',
    uploadProgress: (current: number, total: number) => `${current} / ${total} अपलोड झाले`,
    uploadFailed: 'फोटो अपलोड करण्यात अडचण आली.',
    uploadFailedHint: 'पुन्हा प्रयत्न करा.',
    retry: 'पुन्हा प्रयत्न करा',
    offline: 'इंटरनेट उपलब्ध नाही.\nकृपया पुन्हा प्रयत्न करा.',
    cameraPermission: 'कॅमेरा परवानगी आवश्यक आहे.',
    galleryPermission: 'गॅलरी परवानगी आवश्यक आहे.',
    openSettings: 'सेटिंग्ज उघडा',
    pickerTitle: 'फोटो जोडा',
    morePhotosOverlay: (count: number) => `+${count}`,
  },
} as const;

/** Marathi label for a marketplace category chip. */
export const getCategoryLabel = (category: string): string => {
  const labels = marketplaceStrings.categories as Record<string, string>;
  return labels[category] ?? category;
};

/** Marathi label for a listing status badge. */
export const getStatusLabel = (status: string): string => {
  const labels = marketplaceStrings.status as Record<string, string>;
  return labels[status] ?? status;
};
