export const marketplaceStrings = {
  home: {
    searchPlaceholder: 'Search listings…',
    produceCardTitle: 'Farmer Produce',
    produceCardSubtitle: 'Buy crops directly from farmers',
    produceCardAction: 'Browse Produce',
    productCardTitle: 'Agricultural Products',
    productCardSubtitle: 'Seeds · Fertilizers · Machinery',
    productCardAction: 'Browse Products',
    savedListings: 'Saved Listings',
    myListings: 'My Listings',
    sellSomething: 'Sell Something',
  },
  listings: {
    produceTitle: 'Farmer Produce',
    productsTitle: 'Agricultural Products',
    loading: 'Loading listings…',
    errorTitle: 'Something went wrong',
    retry: 'Retry',
    emptyTitle: 'No listings found',
    emptyMessage: 'Try a different search or category.',
    searchEmptyMessage: 'Try another search term.',
    loadMore: 'Loading more…',
  },
  detail: {
    title: 'Listing Details',
    description: 'Description',
    category: 'Category',
    price: 'Price',
    quantity: 'Quantity',
    seller: 'Seller',
    district: 'District',
    phone: 'Phone',
    posted: 'Posted',
    callSeller: 'Call Seller',
    whatsappSeller: 'WhatsApp Seller',
    loading: 'Loading listing…',
    errorTitle: 'Unable to load listing',
    brand: 'Brand',
    stock: 'Stock',
    crop: 'Crop',
    harvestDate: 'Harvest Date',
    ownerActions: 'Owner Actions',
    soldMessage: 'This listing has been marked as sold.\nIt is no longer visible to buyers.',
    archivedMessage: 'This listing has been archived.\nArchived listings are only visible to you.',
  },
  create: {
    title: 'Sell Something',
    editTitle: 'Edit Listing',
    listingType: 'Listing Type',
    produce: 'Produce',
    product: 'Product',
    crop: 'Crop',
    cropPlaceholder: 'e.g. Onion',
    quantity: 'Quantity',
    unit: 'Unit',
    expectedPrice: 'Expected Price',
    harvestDate: 'Harvest Date',
    harvestDatePlaceholder: 'YYYY-MM-DD',
    productName: 'Product Name',
    productNamePlaceholder: 'e.g. Hybrid Tomato Seeds',
    brand: 'Brand',
    brandPlaceholder: 'e.g. Mahyco',
    category: 'Category',
    stock: 'Stock',
    price: 'Price',
    description: 'Description',
    descriptionPlaceholder: 'Describe your listing…',
    imagesPlaceholder: 'Image upload coming soon',
    publish: 'Publish Listing',
    update: 'Update Listing',
    publishing: 'Publishing…',
    updating: 'Updating…',
    markSold: 'Mark as Sold',
    archive: 'Archive Listing',
    archiving: 'Archiving…',
  },
  myListings: {
    title: 'My Listings',
    active: 'Active',
    sold: 'Sold',
    archived: 'Archived',
    edit: 'Edit',
    archive: 'Archive',
    markSold: 'Mark Sold',
    myListingBadge: 'My Listing',
    emptyTitle: "You haven't created any listings yet.",
    emptyMessage: 'Sell your first product or crop.',
  },
  saved: {
    title: 'Saved Listings',
    emptyTitle: "You haven't saved any listings yet.",
    emptyMessage: 'Tap the heart on a listing to save it.',
  },
  lifecycle: {
    markSoldTitle: 'Mark Listing as Sold?',
    markSoldMessage:
      'This listing will no longer appear in Marketplace.\nYou can still view it inside My Listings.',
    markSoldConfirm: 'Mark Sold',
    archiveTitle: 'Archive Listing?',
    archiveMessage:
      'Archived listings disappear from Marketplace.\nThey remain available in My Listings.',
    archiveConfirm: 'Archive',
    cancel: 'Cancel',
    markedSold: 'Listing marked as sold.',
    archived: 'Listing archived successfully.',
    unableMarkSold: 'Unable to mark listing as sold.',
    unableArchive: 'Unable to archive listing.',
    unableSave: 'Unable to save listing.',
    whatsappUnavailable: 'WhatsApp is not available on this device.',
  },
  errors: {
    timeout: 'Request timed out. Please try again.',
    network: 'Network error. Please check your connection and try again.',
    backendUnavailable: 'Marketplace is temporarily unavailable. Please try again later.',
    validation: 'Please check your listing details and try again.',
    generic: 'Unable to complete this action. Please try again.',
    requiredField: 'This field is required',
    invalidPrice: 'Enter a valid price',
    invalidQuantity: 'Enter a valid quantity',
  },
} as const;
