export const billingStrings = {
  screenTitle: 'Subscription & Billing',
  detailTitle: 'Payment Details',
  profileEntry: 'Subscription & Billing',

  statusActive: 'Active',
  statusExpired: 'Expired',
  statusCancelled: 'Cancelled',
  statusPending: 'Pending',
  statusHalted: 'Payment issue',
  statusPaused: 'Paused',
  statusProcessing: 'Processing',

  currentPlan: 'Current Plan',
  amountPerMonth: (rupees: number) => `₹${rupees}/month`,
  nextBilling: 'Next Billing Date',
  autoRenewal: 'Auto Renewal',
  autoRenewalOn: 'Enabled',
  autoRenewalOff: 'Disabled',
  billingPeriod: 'Current Billing Period',
  renewNow: 'Renew Now',
  subscriptionExpired: 'Subscription Expired',

  planSection: 'Plan details',
  planName: 'Plan Name',
  monthlyAmount: 'Monthly Amount',
  billingFrequency: 'Billing Frequency',
  startedOn: 'Subscription Started',
  currentPeriod: 'Current Period',
  nextRenewal: 'Next Renewal',
  subscriptionId: 'Subscription ID',
  copy: 'Copy',
  copied: 'Copied',

  paymentMethodSection: 'Payment method',
  paymentMethod: 'Payment Method',
  lastUpdated: 'Last Updated',
  methodUnknown: 'Not available yet',

  historySection: 'Billing history',
  historyEmpty: 'No payments yet. Your charges will appear here after each billing cycle.',
  paid: 'Paid',
  failed: 'Failed',
  pending: 'Pending',
  refunded: 'Refunded',

  controlsSection: 'Subscription controls',
  autoRenewExplain:
    'Your subscription renews automatically every month. Cancel anytime — you keep access until the end of the current billing period.',
  cancel: 'Cancel Subscription',
  cancelTitle: 'Cancel subscription?',
  cancelBody:
    'Your subscription will remain active until the end of the current billing period. No future payments will be charged. Cancellation cannot be undone from this screen.',
  cancelConfirm: 'Yes, cancel',
  cancelKeep: 'Keep subscription',
  cancelSuccess: 'Subscription cancelled. Access continues until the period ends.',

  refundSection: 'Refund policy',
  refundBullets: [
    'Full refund within the approved refund window.',
    'After that, the subscription remains active until the billing period ends.',
    'Future renewals stop after cancellation.',
    'Contact support for billing disputes.',
  ],

  supportSection: 'Need help?',
  billingFaq: 'Billing FAQ',
  contactSupport: 'Contact Support',
  comingSoon: 'Coming soon',

  loadError: 'Unable to load subscription details.',
  retry: 'Retry',
  pullHint: 'Pull to refresh',
  amount: 'Amount',
  status: 'Status',
  paymentId: 'Payment ID',
  invoiceId: 'Invoice ID',
  paymentDate: 'Payment Date',
  gateway: 'Gateway',
  transactionRef: 'Transaction Reference',
  receipt: 'Receipt',
  receiptPlaceholder: 'Receipt download will be available soon.',
  noSubscription: 'No subscription found for your account.',
} as const;
