export const subscriptionStrings = {
  title: 'Kissan Agrisathi Subscription',
  subtitle: 'Unlock the full app with a monthly plan',
  amountLabel: '₹100 / month',
  description:
    'Your subscription renews every month. Cancel anytime — you keep access until the end of the paid period.',
  payNow: 'Pay Now',
  retry: 'Retry Payment',
  creating: 'Creating subscription…',
  openingCheckout: 'Opening payment…',
  verifying: 'Verifying payment…',
  refreshing: 'Refreshing status…',
  successTitle: 'Subscription active',
  successBody: 'Welcome to Kissan Agrisathi. Redirecting you to Home…',
  cancelHint: 'Payment cancelled. You can try again anytime.',
  requiredHint: 'An active subscription is required to use the app.',
  monthlyPlan: 'Monthly Plan',
  perMonth: '/ month',
  planTag: 'One simple plan. Full access.',
  featuresHeading: 'Get full access to',
  features: {
    weather: 'Weather Updates',
    mandi: 'Mandi Prices',
    crops: 'Crop Information',
    farmerPrice: 'Expected Prices',
    marketplace: 'Marketplace',
  },
  renews: 'Your subscription renews every month.',
  cancelAnytime: 'Cancel anytime — you keep access until the end of the paid period.',
  razorpay: 'Secure payment powered by Razorpay',
  beforeSubscribe: 'Before you subscribe',
  privacyTitle: 'Privacy Policy',
  privacyHint: 'How we protect your data',
  termsTitle: 'Terms & Conditions',
  termsHint: 'Rules & guidelines',
  refundTitle: 'Refund Policy',
  refundHint: 'Returns & refunds',
  contactTitle: 'Need help? Contact Support',
  contactHint: 'We’re here to help you',
} as const;
