export const marketplaceStrings = {
  home: {
    title: 'बाजारपेठ',
    subtitle: 'शेतकरी ते शेतकरी थेट व्यवहार',
    searchPlaceholder: 'पिके, बियाणे, खते, यंत्र किंवा मजूर शोधा...',
    searchA11y: 'बाजारपेठ शोधा',
    filterA11y: 'शोध आणि फिल्टर',
    lookingForTitle: 'काय शोधत आहात?',
    produceCardTitle: 'शेतमाल',
    produceCardSubtitle: 'महाराष्ट्रातील शेतकऱ्यांकडून थेट खरेदी करा',
    produceCardAction: 'शेतमाल पहा',
    productCardTitle: 'शेती साहित्य',
    productCardSubtitle: 'बियाणे • खते • औषधे • यंत्रे',
    productCardAction: 'साहित्य पहा',
    labourCardTitle: 'मजूर कट्टा',
    labourCardSubtitle: 'शेतीसाठी उपलब्ध मजूर शोधा',
    labourCardAction: 'मजूर शोधा',
    savedListings: 'जतन केलेले',
    savedListingsHint: 'तुमची जतन यादी',
    myListings: 'माझ्या जाहिराती',
    myListingsHint: 'तुमच्या जाहिराती',
    sellSomething: 'नवीन जाहिरात',
    sellSomethingHint: 'विक्रीसाठी पोस्ट करा',
    quickActionsTitle: 'जलद कृती',
    infoA11y: 'बाजारपेठ माहिती',
  },
  saveA11y: 'जाहिरात जतन करा',
  unsaveA11y: 'जतन काढून टाका',
  infoSheet: {
    title: 'बाजारपेठ म्हणजे काय?',
    body: 'इथे शेतकरी एकमेकांकडून शेतमाल खरेदी-विक्री करू शकतात, शेती साहित्य शोधू शकतात आणि शेतीसाठी मजूरही शोधू शकतात.',
    produceTitle: 'शेतमाल',
    produceBody: 'शेतकऱ्यांकडून थेट शेतमाल खरेदी करा',
    productTitle: 'शेती साहित्य',
    productBody: 'बियाणे, खते, औषधे आणि यंत्रे शोधा',
    labourTitle: 'मजूर कट्टा',
    labourBody: 'शेतीसाठी उपलब्ध मजूर शोधा',
    close: 'समजले',
  },
  listings: {
    produceTitle: 'शेतमाल',
    productsTitle: 'शेती साहित्य',
    labourTitle: 'मजूर कट्टा',
    loading: 'जाहिराती लोड होत आहेत…',
    errorTitle: 'काहीतरी चुकले',
    retry: 'पुन्हा प्रयत्न करा',
    emptyTitle: 'कोणतीही जाहिरात सापडली नाही',
    emptyMessage:
      'सध्या कोणतीही जाहिरात उपलब्ध नाही.\n\nकृपया नंतर पुन्हा प्रयत्न करा.',
    searchEmptyMessage: 'आपल्या शोधाशी जुळणारी कोणतीही जाहिरात सापडली नाही.',
    loadMore: 'अजून लोड होत आहे…',
    categoryAll: 'सर्व',
    searchTitle: 'शोधा',
    typeAll: 'सर्व',
    typeProduce: 'शेतमाल',
    typeProduct: 'शेती साहित्य',
    typeLabour: 'मजूर कट्टा',
    loadMoreRetry: 'अजून लोड करण्यात अडचण. पुन्हा प्रयत्न करा.',
  },
  filters: {
    title: 'फिल्टर',
    location: 'स्थान',
    myDistrict: 'माझा जिल्हा',
    allDistricts: 'सर्व जिल्हे',
    otherDistricts: 'इतर जिल्हे',
    sort: 'क्रमवारी',
    sortNewest: 'नवीनतम',
    sortPriceLow: 'कमी किंमत',
    sortPriceHigh: 'जास्त किंमत',
    sortRateLow: 'कमी दैनंदिन दर',
    sortRateHigh: 'जास्त दैनंदिन दर',
    apply: 'लागू करा',
    close: 'बंद करा',
    districtA11y: 'जिल्हा फिल्टर',
    sortA11y: 'क्रमवारी',
  },
  expiry: {
    expired: 'कालबाह्य',
    lastDay: 'आज शेवटचा दिवस',
    tomorrow: 'उद्या संपत आहे',
    daysLeft: (days: number) => `${days} दिवस बाकी`,
  },
  categories: {
    Produce: 'शेतमाल',
    Seeds: 'बियाणे',
    Fertilizers: 'खते',
    Pesticides: 'कीटकनाशके',
    'Farm Machinery': 'शेती यंत्रे',
    Tools: 'साधने',
    Irrigation: 'सिंचन',
    'Crop Protection': 'पीक संरक्षण',
    Harvesting: 'कापणी',
    Plantation: 'लागवड',
    'Sugarcane Cutting': 'ऊस तोडणी',
    Spraying: 'फवारणी',
    Weeding: 'निंदण',
    'Tractor Driver': 'ट्रॅक्टर चालक',
    'Farm Supervisor': 'शेत पर्यवेक्षक',
    'General Labour': 'सामान्य मजूर',
    'Daily Helper': 'दैनिक मदतनीस',
  },
  status: {
    ACTIVE: 'सक्रिय',
    SOLD: 'विकले',
    ARCHIVED: 'संग्रहित',
  },
  labourStatus: {
    ACTIVE: 'उपलब्ध',
    SOLD: 'काम मिळाले',
    ARCHIVED: 'संग्रहित',
  },
  gender: {
    Male: 'पुरुष',
    Female: 'महिला',
    'Mixed Group': 'मिश्र गट',
  },
  rateType: {
    per_day: 'प्रति दिवस',
    per_hour: 'प्रति तास',
  },
  detail: {
    title: 'जाहिरात तपशील',
    description: 'वर्णन',
    category: 'प्रकार',
    price: 'किंमत',
    quantity: 'प्रमाण',
    seller: 'विक्रेता',
    district: 'जिल्हा',
    taluka: 'तालुका',
    village: 'गाव',
    phone: 'मोबाईल',
    posted: 'प्रकाशित',
    callSeller: 'संपर्क करा',
    whatsappSeller: 'व्हॉट्सअॅप',
    contactHint: 'थेट शेतकरी ते शेतकरी संपर्क',
    loading: 'जाहिरात लोड होत आहे…',
    errorTitle: 'जाहिरात लोड करता आली नाही',
    brand: 'ब्रँड',
    stock: 'साठा',
    crop: 'पीक',
    harvestDate: 'कापणीची तारीख',
    availableWorkers: 'उपलब्ध मजूर',
    gender: 'लिंग',
    rate: 'दर',
    availableFrom: 'पासून उपलब्ध',
    individual: 'वैयक्तिक',
    group: 'गट',
    ownerActions: 'आपल्या कृती',
    soldMessage: 'ही जाहिरात विकली म्हणून चिन्हांकित केली आहे.\nती आता खरेदीदारांना दिसणार नाही.',
    hiredMessage: 'ही जाहिरात काम मिळाले म्हणून चिन्हांकित केली आहे.\nती आता इतरांना दिसणार नाही.',
    archivedMessage:
      'ही जाहिरात संग्रहित केली आहे.\nसंग्रहित जाहिराती फक्त आपल्यालाच दिसतात.',
    editListing: 'जाहिरात संपादित करा',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    markHired: 'काम मिळाले म्हणून चिन्हांकित करा',
    archive: 'संग्रहित करा',
    inStock: 'साठा उपलब्ध',
    reportA11y: 'जाहिरात नोंदवा',
    report: 'तक्रार',
    share: 'शेअर',
    shareA11y: 'जाहिरात शेअर करा',
    shareFailed: 'शेअर करता आले नाही. कृपया पुन्हा प्रयत्न करा.',
  },
  create: {
    title: 'नवीन जाहिरात',
    editTitle: 'जाहिरात संपादित करा',
    listingType: 'जाहिरात प्रकार',
    produce: 'शेतमाल',
    product: 'शेती साहित्य',
    labour: 'मजूर कट्टा',
    crop: 'पीक',
    cropPlaceholder: 'पीक निवडा',
    favoriteCropsTitle: '⭐ तुमची प्रमुख पिके',
    allCropsTitle: 'सर्व पिके',
    quantity: 'प्रमाण',
    unit: 'एकक',
    expectedPrice: 'अपेक्षित किंमत',
    harvestDate: 'कापणीची तारीख',
    harvestDatePlaceholder: 'तारीख निवडा',
    selectDate: 'निवडा',
    productName: 'उत्पादनाचे नाव',
    productNamePlaceholder: 'उदा. हायब्रिड टोमॅटो बियाणे',
    brand: 'ब्रँड',
    brandPlaceholder: 'उदा. महिको',
    category: 'प्रकार',
    labourCategory: 'मजूर प्रकार',
    availableWorkers: 'उपलब्ध मजूर',
    gender: 'लिंग',
    rate: 'दर',
    dailyRate: 'दर (प्रति दिवस)',
    rateType: 'दर प्रकार',
    availableFrom: 'पासून उपलब्ध',
    availableFromPlaceholder: 'तारीख निवडा',
    stock: 'साठा',
    price: 'किंमत',
    description: 'वर्णन',
    descriptionPlaceholder: 'आपल्या जाहिरातीबद्दल माहिती लिहा…',
    labourDescriptionPlaceholder: 'कामाचा अनुभव, कौशल्ये किंवा इतर माहिती लिहा…',
    publish: 'जाहिरात प्रकाशित करा',
    published: 'जाहिरात प्रकाशित झाली',
    duplicateImagesHint: 'नवीन जाहिरातीसाठी फोटो पुन्हा निवडा.',
    update: 'जाहिरात अद्यतनित करा',
    publishing: 'प्रकाशित होत आहे…',
    updating: 'अद्यतनित होत आहे…',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    archive: 'संग्रहित करा',
    archiving: 'संग्रहित होत आहे…',
    districtAuto: (district: string) => `📍 जिल्हा: ${district} (आपोआप निवडलेले)`,
    locationAuto: (village: string, taluka: string, district: string) =>
      `📍 ${village}, ${taluka}, ${district} (आपोआप निवडलेले)`,
    districtLoading: '📍 जिल्हा लोड होत आहे…',
    titlePreview: 'शीर्षक',
    sections: {
      photos: 'फोटो',
      listingType: 'जाहिरात प्रकार',
      location: 'स्थान',
      produceDetails: 'शेतमाल तपशील',
      productDetails: 'साहित्य तपशील',
      labourDetails: 'मजूर तपशील',
      quantityPrice: 'प्रमाण आणि किंमत',
      rate: 'दर',
      availability: 'उपलब्धता',
      description: 'वर्णन',
      publish: 'प्रकाशित करा',
    },
    photosCount: (current: number, max: number) => `${current} / ${max}`,
    classifiedNote: 'ही जाहिरात आहे. इन-अॅप खरेदी नाही — खरेदीदार थेट संपर्क करतात.',
  },
  myListings: {
    title: 'माझ्या जाहिराती',
    active: 'सक्रिय',
    sold: 'विकले',
    archived: 'संग्रहित',
    available: 'उपलब्ध',
    hired: 'काम मिळाले',
    edit: 'संपादन करा',
    archive: 'संग्रहित करा',
    markSold: 'विकले म्हणून चिन्हांकित करा',
    markHired: 'काम मिळाले म्हणून चिन्हांकित करा',
    myListingBadge: 'माझी जाहिरात',
    emptyTitle: 'आपण अद्याप कोणतीही जाहिरात तयार केलेली नाही.',
    emptyMessage: 'आजच पहिली जाहिरात द्या.',
    renew: 'पुन्हा प्रकाशित करा',
    renewing: 'प्रकाशित होत आहे…',
    renewed: 'जाहिरात पुन्हा सक्रिय झाली.',
    duplicate: 'हीच जाहिरात पुन्हा',
    duplicatePrefill: 'जाहिरात तयार करण्यासाठी माहिती भरली आहे.',
    moreA11y: 'अधिक कृती',
    unableRenew: 'जाहिरात पुन्हा प्रकाशित करता आली नाही.',
    renewSold: 'विकलेल्या जाहिराती पुन्हा प्रकाशित करता येत नाहीत.',
    renewArchived: 'संग्रहित जाहिराती पुन्हा प्रकाशित करता येत नाहीत.',
    renewNotEligible: 'ही जाहिरात अजून पुन्हा प्रकाशित करण्यायोग्य नाही.',
    renewOwnOnly: 'आपण फक्त आपल्या जाहिराती पुन्हा प्रकाशित करू शकता.',
  },
  saved: {
    title: 'जतन केलेल्या जाहिराती',
    emptyTitle: 'आपण अद्याप कोणतीही जाहिरात जतन केलेली नाही.',
    emptyMessage: 'जाहिरातीवर हृदय चिन्ह दाबून जतन करा.',
    save: 'जतन करा',
  },
  homeSummary: {
    title: 'माझी बाजारपेठ',
    subtitle: 'आपल्या जाहिरातींचा आढावा',
    active: 'सक्रिय',
    sold: 'विकले',
    archived: 'संग्रहित',
    saved: 'जतन',
    viewAll: 'सर्व पहा',
    emptyTitle: 'अद्याप कोणतीही जाहिरात नाही.',
    createFirst: 'पहिली जाहिरात तयार करा',
    loading: 'आढावा लोड होत आहे…',
  },
  lifecycle: {
    markSoldTitle: 'विकले म्हणून चिन्हांकित करायचे?',
    markSoldMessage:
      'ही जाहिरात बाजारपेठेत दिसणार नाही.\nआपण ती माझ्या जाहिराती मध्ये पाहू शकता.',
    markSoldConfirm: 'विकले म्हणून चिन्हांकित करा',
    markHiredTitle: 'काम मिळाले म्हणून चिन्हांकित करायचे?',
    markHiredMessage:
      'ही मजूर जाहिरात बाजारपेठेत दिसणार नाही.\nआपण ती माझ्या जाहिराती मध्ये पाहू शकता.',
    markHiredConfirm: 'काम मिळाले म्हणून चिन्हांकित करा',
    archiveTitle: 'जाहिरात संग्रहित करायची?',
    archiveMessage:
      'संग्रहित जाहिराती बाजारपेठेत दिसणार नाहीत.\nते माझ्या जाहिराती मध्ये उपलब्ध राहतील.',
    archiveConfirm: 'संग्रहित करा',
    cancel: 'रद्द करा',
    markedSold: 'जाहिरात विकली म्हणून चिन्हांकित केली.',
    markedHired: 'जाहिरात काम मिळाले म्हणून चिन्हांकित केली.',
    archived: 'जाहिरात संग्रहित केली',
    unableMarkSold: 'जाहिरात विकली म्हणून चिन्हांकित करता आली नाही.',
    unableMarkHired: 'जाहिरात काम मिळाले म्हणून चिन्हांकित करता आली नाही.',
    unableArchive: 'जाहिरात संग्रहित करता आली नाही.',
    unableSave: 'जाहिरात जतन करता आली नाही.',
    saved: 'जाहिरात जतन केली',
    unsaved: 'जतनातून काढले',
    whatsappUnavailable: 'या उपकरणावर व्हॉट्सअॅप उपलब्ध नाही.',
  },
  report: {
    title: 'जाहिरात नोंदवा',
    subtitle: 'चुकीची किंवा संशयास्पद जाहिरात असेल तर कारण सांगा.',
    reasonRequired: 'कारण निवडा',
    detailsLabel: 'थोडक्यात सांगा',
    detailsPlaceholder: 'काय चुकीचे आहे…',
    detailsRequired: 'इतर कारणासाठी थोडे लिहा',
    submit: 'तक्रार पाठवा',
    submitting: 'पाठवत आहे…',
    cancel: 'रद्द करा',
    success: 'तुमची तक्रार नोंदवली आहे',
    alreadyReported: 'ही जाहिरात तुम्ही आधीच नोंदवली आहे.',
    ownListing: 'स्वतःच्या जाहिरातीवर तक्रार करता येत नाही.',
    failed: 'तक्रार जमत नाही. पुन्हा प्रयत्न करा.',
  },
  reportReasons: {
    FALSE_INFORMATION: 'चुकीची माहिती',
    FAKE_LISTING: 'बनावट जाहिरात',
    FRAUD: 'फसवणूक / संशयास्पद',
    WRONG_PRODUCE: 'चुकीचा शेतमाल',
    INAPPROPRIATE: 'अनुचित सामग्री',
    OTHER: 'इतर',
  },
  errors: {
    timeout: 'वेळ संपला. कृपया पुन्हा प्रयत्न करा.',
    network: 'इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
    backendUnavailable: 'बाजारपेठ तात्पुरती उपलब्ध नाही. कृपया नंतर प्रयत्न करा.',
    validation: 'कृपया तपशील तपासा आणि पुन्हा प्रयत्न करा.',
    generic: 'ही कृती पूर्ण करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
    contactFailed: 'संपर्क करताना समस्या आली. कृपया पुन्हा प्रयत्न करा.',
    tooManyRequests: 'खूप विनंत्या झाल्या. थोड्या वेळाने पुन्हा प्रयत्न करा.',
    requiredField: 'हे फील्ड भरणे आवश्यक आहे',
    invalidPrice: 'वैध किंमत प्रविष्ट करा',
    invalidQuantity: 'वैध प्रमाण प्रविष्ट करा',
    invalidWorkers: 'वैध मजूर संख्या प्रविष्ट करा',
    imagesRequired: 'किमान एक फोटो आवश्यक आहे',
  },
  images: {
    addPhoto: 'फोटो जोडा',
    takePhoto: '📷 फोटो काढा',
    chooseGallery: '🖼️ गॅलरीमधून निवडा',
    removePhoto: 'फोटो हटवा',
    maxReached: 'जास्तीत जास्त ३ फोटो जोडता येतील.',
    maxReachedLabour: 'जास्तीत जास्त २ फोटो जोडता येतील.',
    maxSelected: 'जास्तीत जास्त ३ फोटो निवडा.',
    maxSelectedLabour: 'जास्तीत जास्त २ फोटो निवडा.',
    uploading: 'फोटो अपलोड होत आहेत...',
    uploadProgress: (current: number, total: number) => `${current} / ${total} अपलोड झाले`,
    uploadFailed: 'फोटो अपलोड करण्यात अडचण आली.',
    uploadFailedHint: 'पुन्हा प्रयत्न करा.',
    retry: 'पुन्हा प्रयत्न करा',
    offline: 'इंटरनेट उपलब्ध नाही.\nकृपया पुन्हा प्रयत्न करा.',
    cameraPermission: 'कॅमेरा परवानगी आवश्यक आहे.',
    galleryPermission: 'गॅलरी परवानगी आवश्यक आहे.',
    openSettings: 'सेटिंग्ज उघडा',
    pickerTitle: 'फोटो जोडा',
    morePhotosOverlay: (count: number) => `+${count}`,
  },
} as const;

/** Marathi label for a marketplace category chip. */
export const getCategoryLabel = (category: string): string => {
  const labels = marketplaceStrings.categories as Record<string, string>;
  return labels[category] ?? category;
};

/** Marathi label for a listing status badge (labour uses Available/Hired). */
export const getStatusLabel = (status: string, listingType?: string): string => {
  if (listingType === 'labour') {
    const labourLabels = marketplaceStrings.labourStatus as Record<string, string>;
    return labourLabels[status] ?? status;
  }
  const labels = marketplaceStrings.status as Record<string, string>;
  return labels[status] ?? status;
};

/** Marathi label for labour gender. */
export const getGenderLabel = (gender: string): string => {
  const labels = marketplaceStrings.gender as Record<string, string>;
  return labels[gender] ?? gender;
};

/** Marathi label for labour rate type. */
export const getRateTypeLabel = (rateType: string): string => {
  const labels = marketplaceStrings.rateType as Record<string, string>;
  return labels[rateType] ?? rateType;
};

/** Marathi label for a listing report reason. */
export const getListingReportReasonLabel = (reason: string): string => {
  const labels = marketplaceStrings.reportReasons as Record<string, string>;
  return labels[reason] ?? reason;
};
