/**
 * Centralized, user-facing copy. Never hardcode display strings in screens or
 * components; reference these tokens so the app stays translation-ready.
 */
export const strings = {
  app: {
    name: 'Kisan Katta',
  },
  tabs: {
    home: 'Home',
    market: 'Market',
    community: 'Community',
    marketplace: 'Marketplace',
    profile: 'Profile',
  },
  home: {
    title: 'Home',
    subtitle: 'Your daily farming snapshot',
    placeholder: 'Home content coming soon.',
    weatherTitle: "Today's Weather",
    weatherError: 'Unable to load weather data',
    retry: 'Retry',
    cropsTitle: 'My Favourite Crops',
    cropsSubtitle: 'Kanda · Soyabean · Kapus',
    cropsComing: 'Add favourite crops from your profile',
    marketTitle: "Today's Market Prices",
    marketSubtitle: 'Live mandi rates',
    marketComing: 'Market prices will appear here soon',
    govTitle: 'Government Schemes',
    govSubtitle: 'PM-KISAN, MSP & Maharashtra yojanas',
    govComing: 'Latest government schemes coming soon',
    newsTitle: 'Agriculture News',
    newsSubtitle: 'Farm tips & daily updates',
    newsComing: 'Agriculture news coming soon',
  },
  market: {
    title: 'Market',
    subtitle: 'Live mandi prices and trends',
    searchPlaceholder: 'Search commodity or market',
    loadingMessage: 'Fetching latest mandi prices…',
    errorTitle: 'Something went wrong',
    errorMessage: 'Unable to load market prices. Please check your connection and try again.',
    retry: 'Retry',
    emptyTitle: 'No prices found',
    emptyMessage: 'Try a different search term or filter.',
    modalPriceLabel: 'Modal Price',
    minPriceLabel: 'Min Price',
    maxPriceLabel: 'Max Price',
    perQuintal: 'per quintal',
  },
  community: {
    title: 'Community',
    subtitle: 'Connect with fellow farmers',
    placeholder: 'Community content coming soon.',
  },
  marketplace: {
    title: 'Marketplace',
    subtitle: 'Buy and sell produce and supplies',
    placeholder: 'Marketplace content coming soon.',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Manage your account',
    placeholder: 'Profile content coming soon.',
    editProfile: 'Edit Profile',
    logout: 'Logout',
    logoutConfirmTitle: 'Logout',
    logoutConfirmMessage: 'Are you sure you want to logout?',
    cancel: 'Cancel',
  },
  auth: {
    appTagline: 'Your farming companion',
    mobileTitle: 'Enter Mobile Number',
    mobileSubtitle: "We'll send you a one-time password to verify your number",
    mobilePlaceholder: '9876543210',
    mobileInvalid: 'Please enter a valid 10-digit mobile number',
    continue: 'Continue',
    sendingOtp: 'Sending OTP…',
    otpTitle: 'Verify OTP',
    otpSubtitle: 'Enter the 6-digit code sent to',
    devOtpLabel: 'Developer OTP',
    verifyOtp: 'Verify OTP',
    verifyingOtp: 'Verifying…',
    otpInvalid: 'Please enter the complete 6-digit OTP',
    resendOtp: 'Resend OTP',
    resendOtpIn: 'Resend OTP in',
    changeNumber: 'Change Number',
  },
  completeProfile: {
    title: 'Complete Your Profile',
    subtitle: 'Tell us a bit about your farm so we can personalize your experience',
    nameLabel: 'Full Name',
    namePlaceholder: 'Enter your full name',
    districtLabel: 'District',
    districtPlaceholder: 'Select district',
    talukaLabel: 'Taluka',
    talukaPlaceholder: 'Select taluka',
    villageLabel: 'Village',
    villagePlaceholder: 'Enter your village name',
    cropsLabel: 'Favourite Crops',
    cropsHelper: 'Select up to 10 crops you grow',
    saveProfile: 'Save Profile',

    saving: 'Saving…',
    updateProfile: 'Update Profile',
    updating: 'Updating…',
    nameRequired: 'Name is required',
    districtRequired: 'District is required',
    talukaRequired: 'Taluka is required',
    villageRequired: 'Village is required',
    cropsRequired: 'Select at least one favourite crop',
  },
} as const;
