/**
 * Centralized, user-facing copy. Never hardcode display strings in screens or
 * components; reference these tokens so the app stays translation-ready.
 */
export const strings = {
  app: {
    name: 'Kisan Katta',
  },
  tabs: {
    home: 'Home',
    market: 'Market',
    /** @deprecated Use farmerPrice — kept for any lingering references. */
    community: 'अपेक्षित भाव',
    farmerPrice: 'अपेक्षित भाव',
    marketplace: 'Marketplace',
    profile: 'Profile',
  },
  home: {
    title: 'मुख्यपृष्ठ',
    subtitle: 'तुमचा दैनिक शेती आढावा',
    placeholder: 'मुख्यपृष्ठ लवकरच येत आहे.',
    farmerFallback: 'शेतकरी',
    comingSoon: 'लवकरच येत आहे',
    weatherTitle: 'आजचे हवामान',
    weatherError: 'हवामान माहिती लोड करता आली नाही',
    forecastError: 'हवामान अंदाज लोड करता आला नाही',
    alertsError: 'हवामान सूचना लोड करता आल्या नाहीत',
    retry: 'पुन्हा प्रयत्न करा',
    cropsTitle: 'माझी आवडती पिके',
    cropsSubtitle: 'कांदा · सोयाबीन · कापूस',
    cropsComing: 'प्रोफाइलमधून आवडती पिके जोडा',
    marketTitle: 'आजचे बाजारभाव',
    marketSubtitle: 'थेट मंडी दर',
    marketComing: 'बाजारभाव लवकरच येथे दिसतील',
    govTitle: 'शासकीय योजना',
    govSubtitle: 'पीएम-किसान, किमान आधारभूत किंमत व महाराष्ट्र योजना',
    govComing: 'नवीन शासकीय योजना लवकरच येत आहेत',
    newsTitle: 'शेती बातम्या',
    newsSubtitle: 'शेती टिप्स आणि दैनिक अपडेट',
    newsComing: 'शेती बातम्या लवकरच येत आहेत',
    greetings: {
      morning: 'सुप्रभात',
      afternoon: 'शुभ दुपार',
      evening: 'शुभ संध्याकाळ',
      night: 'शुभ रात्री',
    },
    weather: {
      feelsLike: 'जाणवणारे तापमान',
      feelsLikeShort: 'जाणवते',
      humidity: 'आर्द्रता',
      windSpeed: 'वाऱ्याचा वेग',
      cloudCover: 'ढगांचे प्रमाण',
      rainfallToday: 'आजचा पाऊस',
      windDirection: 'वाऱ्याची दिशा',
      uvIndex: 'अतिनील किरणे',
      updated: 'शेवटचे अद्यतन',
      rainHeavy: 'जोरदार पावसाची शक्यता – शेतातील काम काळजीपूर्वक नियोजन करा',
      rainLikely: 'आज पाऊस अपेक्षित आहे',
      rainPossible: 'आज हलका पाऊस संभवतो',
      rainNone: 'आज पावसाची शक्यता नाही',
      humidityVeryHigh: 'खूप जास्त – बुरशीजन्य रोगाचा धोका',
      humidityHigh: 'जास्त आर्द्रता',
      humidityModerate: 'मध्यम आर्द्रता',
      humidityLow: 'कमी आर्द्रता',
      uvExtreme: 'अतिशय तीव्र अतिनील किरणे',
      uvVeryHigh: 'खूप जास्त अतिनील किरणे',
      uvHigh: 'जास्त अतिनील किरणे',
      uvModerate: 'मध्यम अतिनील किरणे',
      uvLow: 'कमी अतिनील किरणे',
    },
    alerts: {
      title: 'हवामान सूचना',
      noneTitle: 'सध्या कोणताही हवामान इशारा नाही',
      /** Fallback when weather context is not yet available. */
      noneSubtitle: 'शेतीसाठी हवामान अनुकूल आहे.',
    },
    forecast: {
      title: 'हवामान अंदाज',
      subtitle: 'तुमच्या जिल्ह्याचा दैनिक अंदाज',
      today: 'आज',
      weekdays: {
        sun: 'रवि',
        mon: 'सोम',
        tue: 'मंगळ',
        wed: 'बुध',
        thu: 'गुरु',
        fri: 'शुक्र',
        sat: 'शनि',
      },
    },
    conditions: {
      sunny: 'सूर्यप्रकाश',
      clear: 'स्वच्छ आकाश',
      partlyCloudy: 'अंशतः ढगाळ',
      cloudy: 'ढगाळ',
      overcast: 'पूर्ण ढगाळ',
      mist: 'धुके',
      fog: 'दाट धुके',
      haze: 'धूसर वातावरण',
      patchyRainNearby: 'आजूबाजूला हलका पाऊस',
      rain: 'पाऊस',
      lightRain: 'हलका पाऊस',
      moderateRain: 'मध्यम पाऊस',
      heavyRain: 'मुसळधार पाऊस',
      drizzle: 'रिमझिम पाऊस',
      thunderstorm: 'मेघगर्जनेसह पाऊस',
      snow: 'हिमवृष्टी',
      sleet: 'गारा व पाऊस',
    },
  },
  market: {
    title: 'Market',
    subtitle: 'Live mandi prices and trends',
    searchPlaceholder: 'Search commodity or market',
    loadingMessage: 'Fetching latest mandi prices…',
    errorTitle: 'Something went wrong',
    errorMessage: 'Unable to load market prices. Please check your connection and try again.',
    retry: 'Retry',
    emptyTitle: 'No prices found',
    emptyMessage: 'Try a different search term or filter.',
    modalPriceLabel: 'Modal Price',
    minPriceLabel: 'Min Price',
    maxPriceLabel: 'Max Price',
    perQuintal: 'per quintal',
  },
  community: {
    title: 'शेतकऱ्यांचा अपेक्षित भाव',
    subtitle: 'तुमच्या जिल्ह्यातील शेतकऱ्यांचे अपेक्षित विक्री दर',
    placeholder: '',
  },
  farmerPrice: {
    title: 'शेतकऱ्यांचा अपेक्षित भाव',
    subtitle: 'तुमच्या जिल्ह्यातील शेतकऱ्यांचे अपेक्षित विक्री दर',
  },
  marketplace: {
    title: 'Marketplace',
    subtitle: 'Buy and sell produce and supplies',
    placeholder: 'Marketplace content coming soon.',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Manage your account',
    placeholder: 'Profile content coming soon.',
    editProfile: 'प्रोफाइल अपडेट करा',
    editSubtitle: 'तुमची माहिती अद्ययावत ठेवा',
    logout: 'Logout',
    logoutConfirmTitle: 'Logout',
    logoutConfirmMessage: 'Are you sure you want to logout?',
    cancel: 'Cancel',
  },
  auth: {
    appTagline: 'Your farming companion',
    mobileTitle: 'Enter Mobile Number',
    mobileSubtitle: "We'll send you a one-time password to verify your number",
    mobilePlaceholder: '9876543210',
    mobileInvalid: 'Please enter a valid 10-digit mobile number',
    continue: 'Continue',
    sendingOtp: 'Sending OTP…',
    otpTitle: 'Verify OTP',
    otpSubtitle: 'Enter the 6-digit code sent to',
    devOtpLabel: 'Developer OTP',
    verifyOtp: 'Verify OTP',
    verifyingOtp: 'Verifying…',
    otpInvalid: 'Please enter the complete 6-digit OTP',
    resendOtp: 'Resend OTP',
    resendOtpIn: 'Resend OTP in',
    changeNumber: 'Change Number',
  },
  completeProfile: {
    welcome: 'स्वागत आहे! 👋',
    title: 'तुमचे प्रोफाइल पूर्ण करा',
    subtitle:
      'तुमच्या गावानुसार हवामान, बाजारभाव आणि शेतीसंबंधित माहिती वैयक्तिक करण्यासाठी खालील माहिती भरा.',
    progress: 'स्टेप 1 पैकी 1',
    nameLabel: 'पूर्ण नाव',
    namePlaceholder: 'तुमचे पूर्ण नाव लिहा',
    districtLabel: 'जिल्हा',
    districtPlaceholder: 'जिल्हा निवडा',
    talukaLabel: 'तालुका',
    talukaPlaceholder: 'तालुका निवडा',
    villageLabel: 'गाव',
    villagePlaceholder: 'गाव निवडा',
    cropsLabel: 'आवडती पिके',
    cropsHelper: 'जास्तीत जास्त १० पिके निवडा',
    saveProfile: 'प्रोफाइल जतन करा',
    saving: 'जतन करत आहे…',
    updateProfile: 'प्रोफाइल अपडेट करा',
    updating: 'अपडेट करत आहे…',
    creatingStep: 'प्रोफाइल तयार करत आहे...',
    uploadingStep: 'फोटो अपलोड करत आहे...',
    refreshingStep: 'माहिती अद्ययावत करत आहे...',
    doneStep: 'पूर्ण झाले',
    successTitle: 'प्रोफाइल यशस्वीरित्या तयार झाले.',
    successSubtitle: 'आता तुमच्यासाठी वैयक्तिक अनुभव तयार आहे.',
    photoRetryTitle: 'प्रोफाइल तयार झाले',
    photoRetryMessage:
      'तुमचा प्रोफाइल यशस्वीरित्या तयार झाला आहे.\n\nमात्र प्रोफाइल फोटो अपलोड करता आला नाही.\n\nतुम्ही तो नंतरही अपलोड करू शकता.',
    retryUpload: 'पुन्हा प्रयत्न करा',
    skipForNow: 'आत्तासाठी वगळा',
    nameRequired: 'नाव आवश्यक आहे',
    districtRequired: 'जिल्हा निवडणे आवश्यक आहे',
    talukaRequired: 'तालुका निवडणे आवश्यक आहे',
    villageRequired: 'गाव निवडणे आवश्यक आहे',
    cropsRequired: 'किमान एक आवडते पीक निवडा',
  },
} as const;
